In [18]:
mylist = [3, 2, 1]
count=1
for i in mylist
  mylist[i]=count
  count=count+1
end

In [19]:
mylist

3-element Array{Int64,1}:
 3
 2
 1

In [20]:
function test(x)
    if x==1 
        return 1
    end
    if x<=0
        return 0
    end
    return test(x-1)+test(x-2)
end
test(3)

2

In [21]:
summedvals = 3
for k = 1:2:5  
  println(k)
  summedvals = summedvals + k
end
summedvals

1
3
5


12

In [22]:
x = :foo

typeof(x)

Symbol

In [23]:
using Plots
using Plots

In [24]:
f(x) = 3 * x^2 + 6 * x - 9
for x = -5:5    
  println("(",x, ", ", f(x), ")")
end
using Plots
plot(f, -4, 3) # plot f over [-4,4]
plot!(zero, -4, 3)

(-5, 36)
(-4, 15)
(-3, 0)
(-2, -9)
(-1, -12)
(0, -9)
(1, 0)
(2, 15)
(3, 36)
(4, 63)
(5, 96)


In [25]:
data = [1.6800483  -1.641695388; 
        0.501309281 -0.977697538; 
        1.528012113 0.52771122;
        1.70012253 1.711524991; 
        1.992493625 1.891000015;
        2.706075824 -0.463427794;
        2.994931927 -0.443566619;
        3.491852811 -1.275179133;
        3.501191722 -0.690499597;
        4.459924502 -5.516130799;
        4.936965851 -6.001703074;
        5.023289852 -8.36416901;
        5.04233698 -7.924477517;
        5.50739285 -10.77482371;
        5.568665171 -10.9171878]

x,y = data[:,1], data[:,2]

using Plots
plot(x, y, linetype = :scatter, leg = false) 
# scatter(x, y) # this is an alternative method, but does make a legend

In [26]:
testArray = Array{Any}(20)

testArray[end-3:end]


4-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef

In [27]:
using Plots
plot?

LoadError: syntax: incomplete: premature end of input

In [28]:
?plot

search: plot plot! plotly plot3d Plots plot3d! plotlyjs plotattr plotarea



The main plot command. Use `plot` to create a new plot object, and `plot!` to add to an existing one:

```
    plot(args...; kw...)                  # creates a new plot window, and sets it to be the current
    plot!(args...; kw...)                 # adds to the `current`
    plot!(plotobj, args...; kw...)        # adds to the plot `plotobj`
```

There are lots of ways to pass in data, and lots of keyword arguments... just try it and it will likely work as expected. When you pass in matrices, it splits by columns. To see the list of available attributes, use the `plotattr([attr])` function, where `attr` is the symbol `:Series:`, `:Subplot:`, `:Plot` or `:Axis`. Pass any attribute to `plotattr` as a String to look up its docstring; e.g. `plotattr("seriestype")`.


In [29]:
?collect

search: collect Collections get_color_palette



```
collect(element_type, collection)
```

Return an `Array` with the given element type of all items in a collection or iterable. The result has the same shape and number of dimensions as `collection`.

```jldoctest
julia> collect(Float64, 1:2:5)
3-element Array{Float64,1}:
 1.0
 3.0
 5.0
```

```
collect(collection)
```

Return an `Array` of all items in a collection or iterator. For associative collections, returns `Pair{KeyType, ValType}`. If the argument is array-like or is an iterator with the `HasShape()` trait, the result will have the same shape and number of dimensions as the argument.

# Example

```jldoctest
julia> collect(1:2:13)
7-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11
 13
```


In [30]:
collect(1:7)

7-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7

In [31]:
1:7

1:7

In [32]:
[1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

In [33]:
[ 1 2 3 4
5 6 7 8]'

4×2 Array{Int64,2}:
 1  5
 2  6
 3  7
 4  8

In [34]:
x = [1 2 3 4 5 6]'
y = (x-3).^2/4
plot(x,y, marker = :hex, leg=false)
plot!(title="Plot for graded quiz", linewidth = 2, linecolor=:black)

In [35]:
x = [1, 2, 3, 4, 5, 6]
y = (x-3).^2/4
x,y,typeof((x,y))

([1, 2, 3, 4, 5, 6], [1.0, 0.25, 0.0, 0.25, 1.0, 2.25], Tuple{Array{Int64,1},Array{Float64,1}})

In [36]:
x = [1, 2, 3, 4, 5, 6]
y = (x-3).^2/4
plot(x,y, marker = :hex, leg=false, linewidth = 2, linecolor=:black)
plot!(title="Plot for graded quiz")

In [37]:
x = [1 2 3 4 5 6]'
y = (x-3).^2/4
x,y,typeof((x,y))

([1; 2; … ; 5; 6], [1.0; 0.25; … ; 1.0; 2.25], Tuple{Array{Int64,2},Array{Float64,2}})

In [38]:
x = [1 2 3 4 5 6]'
y = (x-3).^2/4
plot(x,y, marker = :hex, leg=false, linewidth = 2, linecolor=:black)
plot!(title="Plot for graded quiz")

In [39]:
x = [1 2 3 4 5 6]
y = (x-3).^2/4
x,y,typeof((x,y))

([1 2 … 5 6], [1.0 0.25 … 1.0 2.25], Tuple{Array{Int64,2},Array{Float64,2}})

In [40]:
x = [1 2 3 4 5 6]
y = (x-3).^2/4
plot(x,y, marker = :hex, leg=false, linewidth = 2, linecolor=:black)
plot!(title="Plot for graded quiz")

In [41]:
using Plots
#pyplot()

In [42]:
epidemic_day = [1, 2, 4]
num_cases_liberia = [0, 100, 399]
num_cases_guinea = [4, 55, 250]

plot(epidemic_day, [num_cases_liberia, num_cases_guinea])

#plot(epidemic_day, num_cases_liberia, num_cases_guinea)