In [1]:
1+1

2

In [2]:
a = [[1, 2, 3] [4, 5, 6] ]
b = [1,2,3]
b*a

LoadError: DimensionMismatch("matrix A has dimensions (3,1), matrix B has dimensions (3,2)")

In [3]:
[2,2,2]

3-element Array{Int64,1}:
 2
 2
 2

In [5]:
typeof(("A", 3, "B", 4, "C", 2))

Tuple{String,Int64,String,Int64,String,Int64}

In [4]:
repmat([1, 2], 3)



6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [12]:
function simple_addition{T <: Int}(x::T, y::T)
  return x + y
end

simple_addition (generic function with 1 method)

In [7]:
simple_addition(5)

LoadError: MethodError: no method matching simple_addition(::Int64)
Closest candidates are:
  simple_addition(::T<:Int64, ::T<:Int64) where T<:Int64 at In[6]:2

In [8]:
simple_addition(x = 5, y = 5)

LoadError: function simple_addition does not accept keyword arguments

In [9]:
simple_addition(5, 5)

10

In [10]:
simple_addition(5., 5.)

LoadError: MethodError: no method matching simple_addition(::Float64, ::Float64)

In [13]:
map(x -> 2x^2 + 3x - 2, 1:2:9)

5-element Array{Int64,1}:
   3
  25
  63
 117
 187

In [14]:
function my_function{T}(a::T, b::T, c::T = 2 + 8im)
  return a - (b * c)
end

my_function (generic function with 2 methods)

In [19]:
my_function(4, 3.5, 8) 

LoadError: MethodError: no method matching my_function(::Int64, ::Float64, ::Int64)
Closest candidates are:
  my_function(::T, ::T, ::T) where T at In[14]:2
  my_function(::T, ::T) where T at In[14]:2

In [20]:
?mapreduce

search: mapreduce mapreducedim



```
mapreduce(f, op, itr)
```

Like `mapreduce(f, op, v0, itr)`. In general, this cannot be used with empty collections (see `reduce(op, itr)`).

```
mapreduce(f, op, v0, itr)
```

Apply function `f` to each element in `itr`, and then reduce the result using the binary function `op`. `v0` must be a neutral element for `op` that will be returned for empty collections. It is unspecified whether `v0` is used for non-empty collections.

[`mapreduce`](@ref) is functionally equivalent to calling `reduce(op, v0, map(f, itr))`, but will in general execute faster since no intermediate collection needs to be created. See documentation for [`reduce`](@ref) and [`map`](@ref).

```jldoctest
julia> mapreduce(x->x^2, +, [1:3;]) # == 1 + 4 + 9
14
```

The associativity of the reduction is implementation-dependent. Additionally, some implementations may reuse the return value of `f` for elements that appear multiple times in `itr`. Use [`mapfoldl`](@ref) or [`mapfoldr`](@ref) instead for guaranteed left or right associativity and invocation of `f` for every value.


In [29]:
?Symbol

search: Symbol



```
Symbol(x...) -> Symbol
```

Create a `Symbol` by concatenating the string representations of the arguments together.


In [36]:
Symbol("\"Foo\"")

Symbol("\"Foo\"")

In [37]:
:"Foo"

"Foo"

In [41]:
typeof(nothing)

Void

In [42]:
using DataFrames

INFO: Precompiling module DataFrames.


In [44]:
?deleterows!

search: deleterows!



No documentation found.

`DataFrames.deleterows!` is a `Function`.

```
# 2 methods for generic function "deleterows!":
deleterows!(df::DataFrames.DataFrame, ind::Union{Integer, UnitRange{Int64}}) in DataFrames at C:\Users\strac_000\.julia\v0.6\DataFrames\src\dataframe/dataframe.jl:800
deleterows!(df::DataFrames.DataFrame, ind::AbstractArray{Int64,1}) in DataFrames at C:\Users\strac_000\.julia\v0.6\DataFrames\src\dataframe/dataframe.jl:807
```
